<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Delete_slds-button slds-button_brand</name>
   <tag></tag>
   <elementGuidId>a343929a-e9a3-4c9e-a627-1d3ea86c7e86</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Confirm']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.slds-button.slds-button_brand</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>75cde608-998a-4fac-a31d-513aeda30aa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-button slds-button_brand</value>
      <webElementGuid>dee0a75e-cf49-4692-9be6-534127d58f6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e1774fa9-8035-4728-bf85-f977ab40003f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Confirm</value>
      <webElementGuid>0838b8ca-7eb5-43e3-a0bc-4085d693f7ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;brandBand_2&quot;)/div[@class=&quot;slds-template__container&quot;]/div[@class=&quot;center oneCenterStage lafSinglePaneWindowManager&quot;]/div[@class=&quot;windowViewMode-normal oneContent active lafPageHost&quot;]/siqic-qr_-list-page-lwc[1]/div[@class=&quot;row&quot;]/section[@class=&quot;slds-modal slds-fade-in-open slds-modal_small&quot;]/div[@class=&quot;slds-modal__container&quot;]/footer[@class=&quot;slds-modal__footer slds-text-align_right&quot;]/input[@class=&quot;slds-button slds-button_brand&quot;]</value>
      <webElementGuid>f306e6d6-9c8f-4834-8dc5-1a63d77bb3fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Confirm']</value>
      <webElementGuid>ee384b45-f38f-4576-b74a-7c27d67f58f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='brandBand_2']/div/div/div/siqic-qr_-list-page-lwc/div/section/div/footer/input</value>
      <webElementGuid>e74e6c50-2cd9-4048-b12c-7c590c65c764</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/input</value>
      <webElementGuid>cd4cd543-3c89-4ee6-a385-f2e5d50ac52a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button']</value>
      <webElementGuid>a8066acc-4cbb-4af2-9a2d-0cfc938561d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
