<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Product</name>
   <tag></tag>
   <elementGuidId>8b50b9d2-937d-4d9e-b162-975de434ce75</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='navbar-inputs-1796']/lightning-combobox/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>lightning-combobox.product-dropdown.slds-form-element > label.slds-form-element__label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>9a05b78c-86db-4487-8078-5a17c1e9fce4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-form-element__label</value>
      <webElementGuid>e732420d-d41d-4396-a15f-f893241b96ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>combobox-button-1798</value>
      <webElementGuid>d95a4dbf-b843-4b62-b52d-519884a3ab85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Product</value>
      <webElementGuid>96bf9591-a95c-42e5-bacd-19daef520a99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbar-inputs-1796&quot;)/lightning-combobox[@class=&quot;product-dropdown slds-form-element&quot;]/label[@class=&quot;slds-form-element__label&quot;]</value>
      <webElementGuid>e611b029-4276-4d81-a9ec-6cc289a880ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbar-inputs-1796']/lightning-combobox/label</value>
      <webElementGuid>0042ba7d-4998-4ed8-bf81-4d69866a770d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='&lt;'])[1]/following::label[1]</value>
      <webElementGuid>2c9cf556-43a1-4bb1-affb-648dcfafb186</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='>'])[1]/following::label[1]</value>
      <webElementGuid>ddddd84f-1dd3-4d7b-aac4-b062d04547b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cresmba'])[1]/preceding::label[1]</value>
      <webElementGuid>8ff342df-09c0-42dd-823a-5405751cb1fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Collapse Tree Branch'])[1]/preceding::label[1]</value>
      <webElementGuid>83b07946-3031-4a25-af37-7dffe1ec2913</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Product']/parent::*</value>
      <webElementGuid>78da34f9-a818-4917-bf8e-7bfff52bd281</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/lightning-combobox/label</value>
      <webElementGuid>9e4726d3-6625-4875-a5a3-5b9fa67de74c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Product' or . = 'Product')]</value>
      <webElementGuid>45f7edc8-8109-42d7-816a-4a05707faedc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
