<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_User Type_slds-checkbox_faux</name>
   <tag></tag>
   <elementGuidId>58f24970-06f2-47dc-87b3-2a056bb3e855</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[div[text()='VAC-REGION']]/preceding-sibling::td/div/lightning-input/div/span/label/span[@part='indicator']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.slds-checkbox_faux</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>92273e5c-5d22-4eaf-b61d-4d42d0141403</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>part</name>
      <type>Main</type>
      <value>indicator</value>
      <webElementGuid>d7d02d7d-f6a3-4820-bbb0-c37cb79f7447</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-checkbox_faux</value>
      <webElementGuid>e6a2d36c-9639-491e-a167-84a4cf93cd68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;VAC-REGION-3396&quot;)/div[@class=&quot;slds-form-element__control slds-grow&quot;]/span[@class=&quot;slds-checkbox&quot;]/label[@class=&quot;slds-checkbox__label&quot;]/span[@class=&quot;slds-checkbox_faux&quot;]</value>
      <webElementGuid>fc3c498b-924c-45aa-b243-e80df2241bb0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//lightning-input[@id='VAC-REGION-3396']/div/span/label/span</value>
      <webElementGuid>e3ad8d03-c819-4743-ba76-f1eaca62f6e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span/label/span</value>
      <webElementGuid>a9cda7d6-6390-4bca-9ab9-cdde68d0708b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
