<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Username</name>
   <tag></tag>
   <elementGuidId>05f691c6-1b86-4d23-9979-a21da6e94152</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='usernamegroup']/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label.label.usernamelabel</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>bb9ab8ea-a3b9-4ed5-9ddd-9f75d4c5f5c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>d41432fe-fc64-4e1e-b30d-a624018f1bc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>label usernamelabel</value>
      <webElementGuid>50ca5d06-1253-4aec-9593-b44a301a7b3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Username</value>
      <webElementGuid>be1215de-7eaa-4c97-9d55-e7f465a20817</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;usernamegroup&quot;)/label[@class=&quot;label usernamelabel&quot;]</value>
      <webElementGuid>882329e3-36f8-4e0e-8500-1d275e3dc1ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='usernamegroup']/label</value>
      <webElementGuid>44a304bf-099e-4bd4-aa90-4b3e45acf7d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::label[1]</value>
      <webElementGuid>66173aa2-379e-4222-b2f3-031361b0ab44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/following::label[1]</value>
      <webElementGuid>2b10cd33-f356-4763-bdea-38b4c688949a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/preceding::label[1]</value>
      <webElementGuid>dca86a80-49b2-4ed2-8603-1b65265f0297</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remember me'])[1]/preceding::label[2]</value>
      <webElementGuid>078541ec-0f3c-4d03-ac8e-d79dcd6dc6f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Username']/parent::*</value>
      <webElementGuid>c652f1fc-ced5-4443-abdb-2dd36033902d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>1369de73-3e72-4859-904b-4106abe7dab6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Username' or . = 'Username')]</value>
      <webElementGuid>056065d6-f16c-48e8-8ab1-f88d6e4b386c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
