<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_12345</name>
   <tag></tag>
   <elementGuidId>9ce0a841-fc1f-40ac-bebd-4084299b2ca7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;a3X5e000000EfFuEAK&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button [text()= '!QATEST']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a5a2f447-37be-49bc-a540-9073b8bf835b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-button</value>
      <webElementGuid>20e203e8-7344-4992-9fa9-d7b530a9e6e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>cd6a873e-41e5-4a8b-9dd2-69ddcdb3db55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a3X5e000000EfFuEAK</value>
      <webElementGuid>870b1a83-c922-4ca9-8f70-7162a544a36b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>!12345</value>
      <webElementGuid>c9194b69-2a2a-4369-96d4-c8042edd3d4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c044d4c3-7cef-4370-b6a2-d76823d7015e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>a3X5e000000EfFuEAK</value>
      <webElementGuid>890eba1a-3595-4ab1-ac00-a11630d63898</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>!12345</value>
      <webElementGuid>1f1ae520-4fad-4c97-98a5-35934aed02b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;brandBand_2&quot;)/div[@class=&quot;slds-template__container&quot;]/div[@class=&quot;center oneCenterStage lafSinglePaneWindowManager&quot;]/div[@class=&quot;windowViewMode-normal oneContent active lafPageHost&quot;]/siqic-qr_-list-page-lwc[1]/div[@class=&quot;row&quot;]/div[@class=&quot;slds-grid slds-p-around--medium&quot;]/div[1]/div[@class=&quot;vertical-scroll&quot;]/div[1]/div[@class=&quot;slds-tree_container&quot;]/ul[@class=&quot;slds-tree&quot;]/li[3]/div[@class=&quot;slds-tree__item&quot;]/lightning-button[@class=&quot;slds-tree__item-label slds-truncate&quot;]/button[@class=&quot;slds-button&quot;]</value>
      <webElementGuid>38cf4657-854b-4d27-9494-ecb87a95230e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='a3X5e000000EfFuEAK']</value>
      <webElementGuid>347c9ed6-4b35-451d-9a31-d58b0fd4da0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='brandBand_2']/div/div/div/siqic-qr_-list-page-lwc/div/div/div/div/div/div/ul/li[3]/div/lightning-button/button</value>
      <webElementGuid>084dc6d7-87a5-4078-86c2-b54d711c7507</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='!1234'])[1]/following::button[1]</value>
      <webElementGuid>606560d0-8528-4aae-9c14-34c4d214a703</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='!'])[1]/following::button[2]</value>
      <webElementGuid>145e909c-eb63-41a0-aa39-08f0bc92cbec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='!123455511'])[1]/preceding::button[1]</value>
      <webElementGuid>0a1a8604-3569-41f4-be56-1ae83def4ac8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='!12QA'])[1]/preceding::button[2]</value>
      <webElementGuid>d33cee2b-f601-4d1d-abe8-b3385e5b7c8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='!12345']/parent::*</value>
      <webElementGuid>be3a45fa-caca-45d1-8ece-58c24d5437ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/lightning-button/button</value>
      <webElementGuid>f8d55601-ee3c-42ee-a595-e7e6b58870a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'a3X5e000000EfFuEAK' and @title = '!12345' and @type = 'button' and (text() = '!12345' or . = '!12345')]</value>
      <webElementGuid>6e5959f8-cec5-4ad8-ade1-f41eac1fea80</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
