<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Name_FolderName</name>
   <tag></tag>
   <elementGuidId>4c14b318-311b-44aa-b4c8-384967d3b0ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-1468</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='FolderName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>54b4ca08-0297-4f74-921c-f14f191979ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-input</value>
      <webElementGuid>05291e8f-ca9c-4245-8e21-6b97e80aba92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1723c75f-87f5-4c36-8233-cc4709cd0886</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-1468</value>
      <webElementGuid>830adde4-7d2f-4b97-a0ba-c90b2cb5eced</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>part</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>47110383-0fef-4bb6-95e3-6beada69d43e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-errormessage</name>
      <type>Main</type>
      <value>help-message-1468</value>
      <webElementGuid>c0298485-e287-428d-b7d0-bf7aed4bd923</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FolderName</value>
      <webElementGuid>7e20d516-92e0-4619-87fd-15a4110e9f8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-1468&quot;)</value>
      <webElementGuid>0ba62dae-6ffe-4593-bd84-9fd6f22803dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-1468']</value>
      <webElementGuid>ef0fd402-6b41-45b7-b62b-c8db3c646c4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='brandBand_2']/div/div/div/siqic-qr_-list-page-lwc/div/div/section/div/div/div/div[2]/lightning-input/div/div/input</value>
      <webElementGuid>cbacd4ee-c5a1-43a3-a772-f70d3062e825</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/lightning-input/div/div/input</value>
      <webElementGuid>a626dd47-3ee6-458b-bd0f-127f1e14314f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'input-1468' and @name = 'FolderName']</value>
      <webElementGuid>f5f00a20-4d35-4591-b27d-93b681ca0006</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
