<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Super Admin Integration_roster-group</name>
   <tag></tag>
   <elementGuidId>cf4c7c06-f86a-4377-bb6d-8334c8eaf22f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#a1D5e000000vxAZEAY-1489</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[.//div[@title='VAC_Roster_22K']]/preceding-sibling::td[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c6e341b6-98e6-4a94-9b04-b1e79a119701</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>roster-radio</value>
      <webElementGuid>9df43018-e585-4c81-b3de-030e8521143c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>1b6eeedc-16ca-4734-962b-c657d5aaa567</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>a1D5e000000vxAZEAY-1489</value>
      <webElementGuid>4a1bbf52-595c-4086-9db0-0ba70275abc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>roster-group</value>
      <webElementGuid>822fea43-3697-49a8-93b8-b19092644338</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>undefined</value>
      <webElementGuid>63d8724d-bcdd-4981-8fe2-6c204eea0d93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a1D5e000000vxAZEAY-1489&quot;)</value>
      <webElementGuid>59af73ad-8e64-4f96-bf81-c6d49dc0bf47</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='a1D5e000000vxAZEAY-1489']</value>
      <webElementGuid>e6a9b973-20d4-4fa4-89ae-4b6c04d6f500</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-content-id-2-1489']/div[2]/table/tbody/tr[20]/td/input</value>
      <webElementGuid>b83ecd7e-e443-498e-94a9-9596318ce70a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/div/div[2]/div[2]/table/tbody/tr[20]/td/input</value>
      <webElementGuid>9fdbc3c2-8b57-4c8c-a749-305ed50039cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'a1D5e000000vxAZEAY-1489' and @name = 'roster-group']</value>
      <webElementGuid>ad70f5ff-9654-47da-be1c-9467c4285c86</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
