<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Super Admin Integration_roster-group</name>
   <tag></tag>
   <elementGuidId>cf4c7c06-f86a-4377-bb6d-8334c8eaf22f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[.//div[@title='VAC_Roster_22K']]/preceding-sibling::td[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#a1D5e000000vxAZEAY-1489</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3f91bfa8-de78-42b3-8930-d1b2f3ded9c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>roster-radio</value>
      <webElementGuid>fb17371e-f94e-4fec-a46f-5229b0afb68b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>cdb770c5-1a40-40a5-a3c8-c210446e10cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>a1D5e000000vxAZEAY-1489</value>
      <webElementGuid>1c018fb3-5a95-4ad1-bef0-d0ac8c9ac740</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>roster-group</value>
      <webElementGuid>20148999-e826-4afd-85e2-4c2746f84040</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>undefined</value>
      <webElementGuid>60a716fe-4d44-4b4c-bd02-0cc0ad65bec4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a1D5e000000vxAZEAY-1489&quot;)</value>
      <webElementGuid>1f3645eb-a557-4189-8989-7af9b50fba0a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='a1D5e000000vxAZEAY-1489']</value>
      <webElementGuid>3434243c-fa6f-4920-a916-4ed1c660fb8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-content-id-2-1489']/div[2]/table/tbody/tr[20]/td/input</value>
      <webElementGuid>f90e338f-5f35-40e9-b269-8358d84bfb60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/div/div[2]/div[2]/table/tbody/tr[20]/td/input</value>
      <webElementGuid>73eaf3c7-47a4-4fc2-b04f-3e88b31578fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'a1D5e000000vxAZEAY-1489' and @name = 'roster-group']</value>
      <webElementGuid>35d853ff-1bac-4f51-9081-848823693532</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
