<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lightning-spinner_Loading</name>
   <tag></tag>
   <elementGuidId>e48c2d85-45c8-4357-8c83-118f77792d47</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>lightning-spinner.loader-background.slds-spinner_container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[(text() = 'QR POCQuota Refinement >  ExitSaveCurrent Stage:DetailsCycle Level ConfigurationsProduct Level ConfigurationsView Refinement*NameName*Business UnitBusiness UnitSelect Business UnitTeamTeamNoneSub TeamSub TeamNone*ProductNone*Time PeriodSelect Time Period*DateDateSelect a date for Date  Period Start DatePeriod Start DateSelect a date for Period Start Date  Period End DatePeriod End DateSelect a date for Period End Date  GoalGoal*RosterRosterCancel and closeGoalsStatusData AdapterNameBusiness UnitProductsFrequencyNameFrequencyVersionLast Modified DateLast Modified ByCancelSaveCancel and closeRosterNamePeriodVersionLast Updated ByLast Updated OnCancelSaveNext' or . = 'QR POCQuota Refinement >  ExitSaveCurrent Stage:DetailsCycle Level ConfigurationsProduct Level ConfigurationsView Refinement*NameName*Business UnitBusiness UnitSelect Business UnitTeamTeamNoneSub TeamSub TeamNone*ProductNone*Time PeriodSelect Time Period*DateDateSelect a date for Date  Period Start DatePeriod Start DateSelect a date for Period Start Date  Period End DatePeriod End DateSelect a date for Period End Date  GoalGoal*RosterRosterCancel and closeGoalsStatusData AdapterNameBusiness UnitProductsFrequencyNameFrequencyVersionLast Modified DateLast Modified ByCancelSaveCancel and closeRosterNamePeriodVersionLast Updated ByLast Updated OnCancelSaveNext')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>lightning-spinner</value>
      <webElementGuid>2e205d10-e839-4c0e-969d-85bd5cb4a0aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>loader-background slds-spinner_container</value>
      <webElementGuid>94c9b2fa-dcb5-4c46-8021-c70a22fe3580</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>variant</name>
      <type>Main</type>
      <value>brand</value>
      <webElementGuid>4b0e6035-dee3-47c1-9e15-3a717212a00c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>medium</value>
      <webElementGuid>7f6d850f-eec1-4471-8fd3-20331bbcc1ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Loading</value>
      <webElementGuid>bd961aa8-90c5-4b7c-a0eb-47287e8d165e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;brandBand_2&quot;)/div[@class=&quot;slds-template__container&quot;]/div[@class=&quot;center oneCenterStage lafSinglePaneWindowManager&quot;]/div[@class=&quot;windowViewMode-normal oneContent active lafPageHost&quot;]/siqic-qr-new-cycle-creation[1]/div[@class=&quot;main-div main&quot;]/div[@class=&quot;form-size form-1&quot;]/c-qr-h-o-details[1]/div[1]/lightning-spinner[@class=&quot;loader-background slds-spinner_container&quot;]</value>
      <webElementGuid>1a205317-bc88-4d8e-9fa8-f6bd764bf0c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='brandBand_2']/div/div/div[2]/siqic-qr-new-cycle-creation/div/div[3]/c-qr-h-o-details/div/lightning-spinner</value>
      <webElementGuid>962aa0af-0725-4aaf-a7c8-2bb4d2db27ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Refinement'])[1]/following::lightning-spinner[1]</value>
      <webElementGuid>a734b0a3-7f67-499d-b6a1-427b90231ea9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Level Configurations'])[1]/following::lightning-spinner[1]</value>
      <webElementGuid>18a3b27f-bf21-4384-8bc4-bb9432fae491</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/preceding::lightning-spinner[1]</value>
      <webElementGuid>d2adb207-4fe7-4b8f-8a84-df646ccf8b6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//lightning-spinner</value>
      <webElementGuid>4199902d-cb40-4256-9fb8-b96a3747fe1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//lightning-spinner[(text() = 'Loading' or . = 'Loading')]</value>
      <webElementGuid>e0af2ac4-c4e0-4a51-a4e1-29b404197ac3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
