<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lightning-spinner_Loading</name>
   <tag></tag>
   <elementGuidId>e48c2d85-45c8-4357-8c83-118f77792d47</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>C</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>lightning-spinner.loader-background.slds-spinner_container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>lightning-spinner</value>
      <webElementGuid>4310a37b-260e-4300-9f28-280ac7df40fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>loader-background slds-spinner_container</value>
      <webElementGuid>7791fd6f-cb22-4ec7-b039-176c070d4e99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>variant</name>
      <type>Main</type>
      <value>brand</value>
      <webElementGuid>72fc793f-bd85-4ef8-ad12-7595bdea9970</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>medium</value>
      <webElementGuid>b35ba6dd-3ff2-4cb7-b411-edad311ea76d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Loading</value>
      <webElementGuid>79d5b5b7-7b37-4de7-9d61-af5c1217ad56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;brandBand_2&quot;)/div[@class=&quot;slds-template__container&quot;]/div[@class=&quot;center oneCenterStage lafSinglePaneWindowManager&quot;]/div[@class=&quot;windowViewMode-normal oneContent active lafPageHost&quot;]/siqic-qr-new-cycle-creation[1]/div[@class=&quot;main-div main&quot;]/div[@class=&quot;form-size form-1&quot;]/c-qr-h-o-details[1]/div[1]/lightning-spinner[@class=&quot;loader-background slds-spinner_container&quot;]</value>
      <webElementGuid>c0aa2698-62fc-4a68-981f-329ec2b066de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='brandBand_2']/div/div/div[2]/siqic-qr-new-cycle-creation/div/div[3]/c-qr-h-o-details/div/lightning-spinner</value>
      <webElementGuid>25d2abb3-11fe-49bd-9062-5d9f588fc46b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Refinement'])[1]/following::lightning-spinner[1]</value>
      <webElementGuid>427c6869-0edb-45a8-bede-78d00b5a7cc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Level Configurations'])[1]/following::lightning-spinner[1]</value>
      <webElementGuid>d3d23e92-fcd7-47e8-85c4-bd0750e11fcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/preceding::lightning-spinner[1]</value>
      <webElementGuid>54454ec0-11e4-4f9e-a624-42efcbfdff11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//lightning-spinner</value>
      <webElementGuid>db1d96ea-dc06-4df3-8022-8782d299b63b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//lightning-spinner[(text() = 'Loading' or . = 'Loading')]</value>
      <webElementGuid>582c3f6a-2dea-4037-9599-765f5109bff5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
