<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Vac</name>
   <tag></tag>
   <elementGuidId>c378b599-1046-4da0-adc6-9f2746db2bf9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//lightning-base-combobox-item[@data-value = 'VAC']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#combobox-button-1493-15-1493 > span.slds-media__body</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2027a099-8b6e-4cf7-b64a-4e5a518cddc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-media__body</value>
      <webElementGuid>40a1e2bd-73e3-4ad9-85bd-83f0b08cdadc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Vac</value>
      <webElementGuid>a02f75a0-849c-4bba-9506-5b4bf8a3b12b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;combobox-button-1493-15-1493&quot;)/span[@class=&quot;slds-media__body&quot;]</value>
      <webElementGuid>46c83c23-26fa-43bc-b6d0-c556ca6c340e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//lightning-base-combobox-item[@id='combobox-button-1493-15-1493']/span[2]</value>
      <webElementGuid>95d232c5-cd9f-4bd6-9513-fb3ff88a41fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This Is To Test 40 Character Length In The Name Of Bu For'])[1]/following::span[2]</value>
      <webElementGuid>bab219c8-0f24-4d0c-8869-ea13befe88e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Testing', &quot;'&quot;, ' Spchar', &quot;'&quot;, 'so That !@#$%^&amp;*()-={}[]&lt;>.?:')])[1]/following::span[5]</value>
      <webElementGuid>66c0765e-35da-4e18-8d72-6bd1e3942c21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Women', &quot;'&quot;, 's Care')])[1]/preceding::span[6]</value>
      <webElementGuid>c68371d6-8d49-42e9-8609-2d9a0c0596b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//lightning-base-combobox-item[16]/span[2]</value>
      <webElementGuid>c7e9a350-ab22-44c1-b532-7cb8adaa8a58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Vac' or . = 'Vac')]</value>
      <webElementGuid>65629d6a-b2fe-4157-995c-c29b0f9467d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
