<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Alpha</name>
   <tag></tag>
   <elementGuidId>e89d84cb-159c-40db-bcae-33206a87c6b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#combobox-button-1497-0-1497 > span.slds-media__body</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[text()='Alpha']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>baa2640e-c21e-470d-9278-17da544dbb9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-media__body</value>
      <webElementGuid>91b8fced-6885-4263-9af6-7b3d00a4c7bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Alpha</value>
      <webElementGuid>0be8aede-35a9-4c4a-832f-fdd51b615307</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;combobox-button-1497-0-1497&quot;)/span[@class=&quot;slds-media__body&quot;]</value>
      <webElementGuid>44a7d619-db09-4ecb-90bb-3f60b8bdc32c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//lightning-base-combobox-item[@id='combobox-button-1497-0-1497']/span[2]</value>
      <webElementGuid>85399d36-3f7d-4eca-8a78-d2d8108d8efa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Team'])[1]/following::span[3]</value>
      <webElementGuid>ff8f4657-7302-4f82-bacc-2dc68c0e6b4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Team'])[2]/following::span[4]</value>
      <webElementGuid>593f2713-312f-41e5-820b-e7e29bbeaf1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sub Team'])[1]/preceding::span[2]</value>
      <webElementGuid>6b23962a-c0e5-4b01-810e-841d6fa5c04f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/lightning-combobox/div/lightning-base-combobox/div/div[2]/lightning-base-combobox-item/span[2]</value>
      <webElementGuid>4236d1d3-b021-4c11-a1e0-11e220077f2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Alpha' or . = 'Alpha')]</value>
      <webElementGuid>13d0f8ba-3a2b-4b1a-ac6e-8459aeecf9c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
