<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Vac</name>
   <tag></tag>
   <elementGuidId>c378b599-1046-4da0-adc6-9f2746db2bf9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#combobox-button-1493-15-1493 > span.slds-media__body</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//lightning-base-combobox-item[@data-value = 'VAC']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>14f834eb-4268-4876-8615-28e1fc4d683a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-media__body</value>
      <webElementGuid>548fddeb-72d7-4e82-b375-79f70df4915e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Vac</value>
      <webElementGuid>380445f4-ccfc-4a7c-bd21-305c0d4901a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;combobox-button-1493-15-1493&quot;)/span[@class=&quot;slds-media__body&quot;]</value>
      <webElementGuid>2d01f655-ffdc-4658-80eb-6095f2038f55</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//lightning-base-combobox-item[@id='combobox-button-1493-15-1493']/span[2]</value>
      <webElementGuid>c2a1912a-434d-427c-8364-6bc93eb51cfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This Is To Test 40 Character Length In The Name Of Bu For'])[1]/following::span[2]</value>
      <webElementGuid>ce9af27f-74e6-4b8e-950f-20f447a844d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Testing', &quot;'&quot;, ' Spchar', &quot;'&quot;, 'so That !@#$%^&amp;*()-={}[]&lt;>.?:')])[1]/following::span[5]</value>
      <webElementGuid>95f83b40-0fb6-4e1d-a559-807e9b3888f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Women', &quot;'&quot;, 's Care')])[1]/preceding::span[6]</value>
      <webElementGuid>ee21616f-1958-439d-ac1d-0244fe90b83d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//lightning-base-combobox-item[16]/span[2]</value>
      <webElementGuid>e8ed5dec-d3a2-4b29-9060-e6746a200732</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Vac' or . = 'Vac')]</value>
      <webElementGuid>7a7021f5-dba2-45ac-bc9e-e64643b7919e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
