<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_GARDASIL</name>
   <tag></tag>
   <elementGuidId>ddd5f7cc-cec4-4d7c-b6ae-593f55620ce6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#GARDASIL-1489 > span.slds-media__body</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[(text() = 'CRESMBA')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c36fa843-0e3c-4dbc-9ef4-676af23c435b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-media__body</value>
      <webElementGuid>2e346144-d12a-4086-b608-f5b2a046ec80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>GARDASIL</value>
      <webElementGuid>22ebb936-3d75-41fa-bde3-2ae0c7ed9639</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GARDASIL-1489&quot;)/span[@class=&quot;slds-media__body&quot;]</value>
      <webElementGuid>1b45af65-8bf8-49f1-a5ea-3a255eae3ecd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='GARDASIL-1489']/span[2]</value>
      <webElementGuid>3bbd1a07-c10c-4b40-bd07-378600bce771</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CRESMBA'])[1]/following::span[3]</value>
      <webElementGuid>73b33821-1ca9-4855-9930-f2cf2e948242</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All'])[2]/following::span[7]</value>
      <webElementGuid>c61b3a5e-ebe1-48fa-9ea4-59a9e2c71f23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GARDASIL 9'])[1]/preceding::span[4]</value>
      <webElementGuid>876eb269-a7db-4971-af42-b9f467c54e73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/span[2]</value>
      <webElementGuid>05b5ee16-d3b3-4d35-a4ae-88efeac4d696</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'GARDASIL' or . = 'GARDASIL')]</value>
      <webElementGuid>94a3cff5-becb-4fd2-9af7-dd85f5d4256d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
