<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_GARDASIL</name>
   <tag></tag>
   <elementGuidId>ddd5f7cc-cec4-4d7c-b6ae-593f55620ce6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[(text() = 'CRESMBA')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#GARDASIL-1489 > span.slds-media__body</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1acd2df7-5fba-4260-8e36-b32cdb3775f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-media__body</value>
      <webElementGuid>88570bd0-efa0-43fc-b04c-963f1f5241a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>GARDASIL</value>
      <webElementGuid>8f16b152-4aea-46fb-b0c2-84f177b55aea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GARDASIL-1489&quot;)/span[@class=&quot;slds-media__body&quot;]</value>
      <webElementGuid>9aab6aec-e2cf-4d52-8e4d-6ad31144b490</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='GARDASIL-1489']/span[2]</value>
      <webElementGuid>b34ec151-3e04-4ad0-b9cd-2880362fd669</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CRESMBA'])[1]/following::span[3]</value>
      <webElementGuid>97441e4f-c55e-47ed-911e-8236f8a2c8e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All'])[2]/following::span[7]</value>
      <webElementGuid>a92cd19d-fda5-42a4-96db-4b22438cc9c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GARDASIL 9'])[1]/preceding::span[4]</value>
      <webElementGuid>5ef6048e-125a-41b9-9009-cddf7e649e1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/span[2]</value>
      <webElementGuid>a3ffd69e-cc37-40db-9ebe-6257811db343</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'GARDASIL' or . = 'GARDASIL')]</value>
      <webElementGuid>5b0ce8c9-1c01-4052-8eac-6e2cd63ae0d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
