<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_View Full Hierarchy</name>
   <tag></tag>
   <elementGuidId>c9b45963-3382-4f95-8748-ba3b8a54c3e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[179]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>lightning-button.slds-m-left_x-small > button.slds-button.slds-button_neutral</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>76e4ed25-b3f3-486b-ad17-429e636cf4e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-button slds-button_neutral</value>
      <webElementGuid>1d0c1982-0642-433e-80bd-25f828daf1b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4aae191d-21fe-4606-a6a5-182051e8959e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>View Full Hierarchy</value>
      <webElementGuid>9aaaf318-fc55-4976-a135-3c0a2a41bf33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a00248a0-ad85-47a9-ae27-83f8007cf066</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View Full Hierarchy</value>
      <webElementGuid>f6382211-e3cc-4cf6-a894-52fdd2ef8ecb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;brandBand_2&quot;)/div[@class=&quot;slds-template__container&quot;]/div[@class=&quot;center oneCenterStage lafSinglePaneWindowManager&quot;]/div[@class=&quot;windowViewMode-normal oneContent active lafPageHost&quot;]/siqic-qr-new-cycle-creation[1]/div[@class=&quot;main-div main&quot;]/div[@class=&quot;form-size form-4&quot;]/c-qr-h-o-view-refinement[1]/div[@class=&quot;tab-List tab-Refinement&quot;]/div[2]/c-qr-refinement-panel-read-only[1]/div[@class=&quot;slds-grid page-height&quot;]/div[@class=&quot;slds-col slds-size_6-of-6&quot;]/div[@class=&quot;padding-t-b&quot;]/div[@class=&quot;slds-grid&quot;]/div[@class=&quot;slds-col slds-size_2-of-6 comments&quot;]/lightning-button[@class=&quot;slds-m-left_x-small&quot;]/button[@class=&quot;slds-button slds-button_neutral&quot;]</value>
      <webElementGuid>7a895285-40b0-4446-b518-3ba3735974df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[179]</value>
      <webElementGuid>ed6276fe-5a6b-4f27-bb3b-32204d79ed96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='brandBand_2']/div/div/div[2]/siqic-qr-new-cycle-creation/div/div[6]/c-qr-h-o-view-refinement/div/div[2]/c-qr-refinement-panel-read-only/div/div/div/div/div[2]/lightning-button/button</value>
      <webElementGuid>c4d928b7-30eb-49fc-b6d2-fe5320781af1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change'])[1]/following::button[1]</value>
      <webElementGuid>1772520c-7242-4a71-b545-279e162d9c9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Proposed Goals'])[1]/following::button[1]</value>
      <webElementGuid>9248b227-249a-4d68-b189-1309b2e00b01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nguyen Thanh Luan'])[2]/preceding::button[1]</value>
      <webElementGuid>99a824a9-3e24-43d0-bc5a-cfcf6fa05ef8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Position Name'])[1]/preceding::button[1]</value>
      <webElementGuid>90778098-3d7b-4d71-9683-0032151012db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='View Full Hierarchy']/parent::*</value>
      <webElementGuid>764f1aa3-4ab6-4053-a70e-c2fa9c8974ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/lightning-button/button</value>
      <webElementGuid>45c531f3-5caf-4019-92b5-4c7d7038dbcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@title = 'View Full Hierarchy' and @type = 'button' and (text() = 'View Full Hierarchy' or . = 'View Full Hierarchy')]</value>
      <webElementGuid>a0382f16-eaf2-4072-b237-93f7b45ab1c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
