<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Delegation</name>
   <tag></tag>
   <elementGuidId>7af9e0f9-794b-411e-b173-856725102bc4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h1[text()='Delegation']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#modal-heading-01-3396</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>73d2cebe-a049-431f-b0c2-51e032844f7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-modal__title slds-hyphenate</value>
      <webElementGuid>2d7a49d7-9fc0-4b99-87d3-7c0ce232aabf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>modal-heading-01-3396</value>
      <webElementGuid>02b9941a-d9e9-4f28-88b4-8c23aa157acd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Delegation</value>
      <webElementGuid>a2eff4b4-35b8-4298-b671-8ab50140d466</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-heading-01-3396&quot;)</value>
      <webElementGuid>0893dcbe-46b8-45b8-88f8-cb394ee1c2ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h1[@id='modal-heading-01-3396']</value>
      <webElementGuid>60c46752-7887-48ac-a7b3-fb06e621217b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='brandBand_2']/div/div/div[3]/siqic-qr_-list-page-lwc/div/div/div[3]/c-qr-delegate-lwc/div/section/div/div/h1</value>
      <webElementGuid>0f8b157f-6990-4f1c-967d-d5fe6f4f4d79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel and close'])[1]/following::h1[1]</value>
      <webElementGuid>fac72414-4de9-4455-973d-6a0efc1eb22c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show Action'])[560]/following::h1[1]</value>
      <webElementGuid>9f2cf772-581e-4fd0-81d1-dc536147c713</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Type'])[1]/preceding::h1[1]</value>
      <webElementGuid>2d9d2b59-4689-4352-9cd9-22f099ed348a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HO'])[1]/preceding::h1[1]</value>
      <webElementGuid>5b84d8aa-cc21-4ded-b261-469fb91e45c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Delegation']/parent::*</value>
      <webElementGuid>282f16c6-8994-43b4-800b-b302232811cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>4d0543e2-84c0-4613-9f40-5abcc757e8a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[@id = 'modal-heading-01-3396' and (text() = 'Delegation' or . = 'Delegation')]</value>
      <webElementGuid>f887659c-ddba-494e-ba4f-cd973071496c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
