<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Business Unit_slds-radio_faux</name>
   <tag></tag>
   <elementGuidId>08567d5d-7ac4-4f1e-a8c0-acafc34c62d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[div[text()='${GlobalVariable.RosterName}']]/preceding-sibling::td//span[contains(@class, 'slds-radio_faux')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.slds-radio_faux</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3dd09586-8e83-46a6-aaaf-ea0917644ea3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-radio_faux</value>
      <webElementGuid>a2b3addb-205f-4e4b-bc04-2dfe90a1550b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-content-id-1-3396&quot;)/div[@class=&quot;delegation-table&quot;]/table[@class=&quot;slds-table slds-table_cell-buffer slds-table_bordered slds-table_col-bordered table-side-borders&quot;]/tbody[1]/tr[@class=&quot;slds-hint-parent&quot;]/td[1]/span[@class=&quot;slds-radio&quot;]/label[@class=&quot;slds-radio__label&quot;]/span[@class=&quot;slds-radio_faux&quot;]</value>
      <webElementGuid>19dd9ae0-4518-4ba6-8179-97a5b8a8cab4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-content-id-1-3396']/div[2]/table/tbody/tr/td/span/label/span</value>
      <webElementGuid>633be984-1f2d-4c91-94c6-36aad21d7223</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/span</value>
      <webElementGuid>1dd9e7ae-7ceb-4cda-8ad0-b5f5fc2e94b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
