<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_12345</name>
   <tag></tag>
   <elementGuidId>d3a9c168-749d-41e9-8066-9d25ec9cb9a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button [text()= '${GlobalVariable.downloadfolder}']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;a3X5e000000EfFuEAK&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>be3c8040-b923-4f4b-86e7-c146f6351dd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-button</value>
      <webElementGuid>114317fb-22f7-482d-ab01-0585fc6313d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a2ae0561-bb60-4041-8b72-23f37abff8f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a3X5e000000EfFuEAK</value>
      <webElementGuid>d0abce34-ff34-48a5-b37b-28056b1f3d88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>!12345</value>
      <webElementGuid>5af28302-5738-4e7b-9543-07fc53bf9a5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>525cb879-3523-4eed-b254-9dec6261ee3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>a3X5e000000EfFuEAK</value>
      <webElementGuid>e3080cfb-e744-4148-9ca3-8d7314549cf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>!12345</value>
      <webElementGuid>35be9e9e-a2dc-4537-8af0-5159fbfeabbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;brandBand_2&quot;)/div[@class=&quot;slds-template__container&quot;]/div[@class=&quot;center oneCenterStage lafSinglePaneWindowManager&quot;]/div[@class=&quot;windowViewMode-normal oneContent active lafPageHost&quot;]/siqic-qr_-list-page-lwc[1]/div[@class=&quot;row&quot;]/div[@class=&quot;slds-grid slds-p-around--medium&quot;]/div[1]/div[@class=&quot;vertical-scroll&quot;]/div[1]/div[@class=&quot;slds-tree_container&quot;]/ul[@class=&quot;slds-tree&quot;]/li[3]/div[@class=&quot;slds-tree__item&quot;]/lightning-button[@class=&quot;slds-tree__item-label slds-truncate&quot;]/button[@class=&quot;slds-button&quot;]</value>
      <webElementGuid>45b64de1-0031-44eb-a1f2-1f21ace7d15d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='a3X5e000000EfFuEAK']</value>
      <webElementGuid>93d1ea1d-a9d9-465f-9bcd-8f91ea940685</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='brandBand_2']/div/div/div/siqic-qr_-list-page-lwc/div/div/div/div/div/div/ul/li[3]/div/lightning-button/button</value>
      <webElementGuid>e31beb1b-deeb-4f97-ab7d-8bbcbe0d52d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='!1234'])[1]/following::button[1]</value>
      <webElementGuid>213d4631-ef31-42f9-befa-f4c3b03e193e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='!'])[1]/following::button[2]</value>
      <webElementGuid>1163f7e1-0810-4f63-8044-0d729c1cfaf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='!123455511'])[1]/preceding::button[1]</value>
      <webElementGuid>1b0e064d-6062-4600-abd8-1c446fb36ddf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='!12QA'])[1]/preceding::button[2]</value>
      <webElementGuid>ef7bb964-d1dc-45e3-9f16-ac789ca7e0dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='!12345']/parent::*</value>
      <webElementGuid>18f1a359-5419-4e7c-9a38-21fe529b2e07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/lightning-button/button</value>
      <webElementGuid>3e790b6e-fe98-4afc-a0b3-e8189a5987d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'a3X5e000000EfFuEAK' and @title = '!12345' and @type = 'button' and (text() = '!12345' or . = '!12345')]</value>
      <webElementGuid>161a9ba6-e578-4d69-b4e9-703afebec38f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
