<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_HO</name>
   <tag></tag>
   <elementGuidId>42238b49-8211-4b0f-9596-12b68f1b1834</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='User Type']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#combobox-button-2312</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d87d075e-3b3a-4fb8-a29b-edef42e3b9bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-combobox__input slds-input_faux slds-combobox__input-value</value>
      <webElementGuid>60b7fd81-5aa8-419e-9558-2c2dc3f14bc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>combobox-button-2312</value>
      <webElementGuid>3ec02045-eaed-41af-9499-a6cd912fd3bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3e9a030f-69d0-43f4-9f78-f0a57c6ae54b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>59f53e25-8c15-4259-bb19-acdb17280475</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>c69f9d22-372e-4778-b085-ad5b1d100e91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>User Type</value>
      <webElementGuid>1230aea6-eae3-4110-90c7-cfbe25b47df2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>baf25c61-c148-4026-aec8-da70b3950b17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>HO</value>
      <webElementGuid>4ca82150-0c4e-4811-a766-1e4aed53f4b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>User Type, HO</value>
      <webElementGuid>49325234-468a-4b74-bbe3-ac26e1bd688f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>54a2fede-068a-4cbd-91f5-c908a0b6203d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>dropdown-element-2312</value>
      <webElementGuid>603e6da4-9ce3-4704-9459-06e9bbd9837b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>HO</value>
      <webElementGuid>539d01ef-ec93-4bed-8fb6-7ce16afdf73a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;combobox-button-2312&quot;)</value>
      <webElementGuid>03308f37-044f-4304-9d3c-5089f7d0937b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='combobox-button-2312']</value>
      <webElementGuid>781166bf-b9e8-4bce-9463-283e51c39def</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-content-id-1-2308']/div/div/lightning-combobox/div/lightning-base-combobox/div/div/button</value>
      <webElementGuid>695ab190-a360-4c98-817d-eba43fbe3427</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Type'])[1]/following::button[1]</value>
      <webElementGuid>f5d02134-abb3-430a-bcd2-ccffac677c08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delegation'])[1]/following::button[1]</value>
      <webElementGuid>8a9dabbd-015c-453a-ba6d-b9392f60da52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Source'])[1]/preceding::button[1]</value>
      <webElementGuid>bb444ef6-e152-4d68-b6e7-ed4aa7de159d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/lightning-combobox/div/lightning-base-combobox/div/div/button</value>
      <webElementGuid>5cb20e53-846b-4420-a5a1-ebd82c5c219d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'combobox-button-2312' and @type = 'button' and @name = 'User Type' and (text() = 'HO' or . = 'HO')]</value>
      <webElementGuid>617621d4-cbd1-46c3-9c55-c8cdf9f86eb9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
