<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Product</name>
   <tag></tag>
   <elementGuidId>92e9aaac-91e5-4853-81f2-04474af1fdb1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='navbar-inputs-1796']/lightning-combobox/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>lightning-combobox.product-dropdown.slds-form-element > label.slds-form-element__label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>bda245f5-9910-4c0d-bdd6-21b7e3f3ebd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-form-element__label</value>
      <webElementGuid>bff65e40-f671-41e8-82c1-59519e2a8795</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>combobox-button-1798</value>
      <webElementGuid>ce0d7932-9566-4af9-b496-69afc643f1a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Product</value>
      <webElementGuid>d19b1315-f267-49d8-ae36-d0dcbe211d8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbar-inputs-1796&quot;)/lightning-combobox[@class=&quot;product-dropdown slds-form-element&quot;]/label[@class=&quot;slds-form-element__label&quot;]</value>
      <webElementGuid>b45d7184-9f66-4481-81c9-e77fcb827c4a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbar-inputs-1796']/lightning-combobox/label</value>
      <webElementGuid>3bbbeeb9-3747-408d-b28c-317610186029</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='&lt;'])[1]/following::label[1]</value>
      <webElementGuid>198630de-204a-429d-8ce2-c9694ab78cbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='>'])[1]/following::label[1]</value>
      <webElementGuid>9ae91157-c762-4aff-9a4a-19bec2542758</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cresmba'])[1]/preceding::label[1]</value>
      <webElementGuid>e18791b1-1d4e-4963-bd7a-44aaad947bf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Collapse Tree Branch'])[1]/preceding::label[1]</value>
      <webElementGuid>e825554b-c763-421f-b73f-654884bd6476</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Product']/parent::*</value>
      <webElementGuid>bf88cb6b-7c1b-47aa-b3ea-5a6d1298fb92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/lightning-combobox/label</value>
      <webElementGuid>8cd77667-f704-4769-8658-edd7c8ca674f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Product' or . = 'Product')]</value>
      <webElementGuid>aaa08099-a152-4cec-9f8b-25da35f127b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
