<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_User Type_slds-checkbox_faux</name>
   <tag></tag>
   <elementGuidId>d9fa5608-e244-4fd2-886e-feb33268f972</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[div[text()='VAC-REGION']]/preceding-sibling::td/div/lightning-input/div/span/label/span[@part='indicator']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.slds-checkbox_faux</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>10663222-50bb-4bdd-998d-ead0e4df908d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>part</name>
      <type>Main</type>
      <value>indicator</value>
      <webElementGuid>2d041c80-ae5a-4af0-acc4-3e3c53ff3b49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-checkbox_faux</value>
      <webElementGuid>17f997be-6d3c-4563-aa84-7e761741efb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;VAC-REGION-3396&quot;)/div[@class=&quot;slds-form-element__control slds-grow&quot;]/span[@class=&quot;slds-checkbox&quot;]/label[@class=&quot;slds-checkbox__label&quot;]/span[@class=&quot;slds-checkbox_faux&quot;]</value>
      <webElementGuid>9471eaaf-770d-411f-b214-f7739a8e74d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//lightning-input[@id='VAC-REGION-3396']/div/span/label/span</value>
      <webElementGuid>6ce614f5-8c1f-4ce8-a06f-8fc70faccc06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span/label/span</value>
      <webElementGuid>63b0b9e1-5a15-4067-baa6-3ae943e2eb03</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
